# Generated by Django 5.1.4 on 2024-12-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
