# Generated by Django 5.1.4 on 2024-12-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
